name: Integration Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest
        python-version: [ 3.8 ] # , 3.5, 3.6, 3.7, 3.8, 3.9 ]
        java-version: [ 8 ]
      fail-fast: false
    steps:
      - name: Checkout Talend/labs-beam-ml
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare lucidoitdoit wheel
        working-directory: ./lucidoitdoit
        run: |
          python -m pip install --upgrade pip setuptools wheel
          ./setup.py install
          ./setup.py sdist bdist_wheel
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache maven artifacts
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Pipeline with Direct Runner
        run: |
          cp -v ./lucidoitdoit/dist/lucidoitdoit-0.1-py3-none-any.whl /tmp
          cd java
          mvn -B -e clean compile exec:java -Dexec.mainClass=com.talend.labs.beam.transforms.python.examples.Uppercase -Dexec.args="--serverInvokerPath=\"$GITHUB_WORKSPACE/lucidoitdoit/bin/lucisetup\""
