name: Python Server CI
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
      fail-fast: false
    steps:
      - name: Checkout Talend/labs-beam-ml
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          pip install docopt avro
          cd lucidoitdoit
          ./setup.py test
